
behaviors:
  TacticalCombatAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 640
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
    
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000

# time_scale은 behaviors 밖에 위치
environment_parameters:
  time_scale: 20